# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2b82f2291e198597963b78029e25e48dbf90fb2102a5033f514d10f89e72f013a6edf022102b8616aa601adc2251590b0d9c3e487e1c31381c96b60768a50ccd

test:
  secret_key_base: 9a30d428d111d110fdd3537c2df611ff26be636af686132d037bf0a954c55f1be0812f1d561512a76d6bd6f3e605b45073ec4830b90ac0e4b611be01f84c6db7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
